### ISSUE TITLE
Patching and compilation functionality

### ISSUE THREAD

**Issue by DebyKatz** [ChrisTimperley/start_stack#20]
I would like a function that takes care of compilation. 
Something like: `compile(source_code_version, patch=patch)` returns `sitl_binary`
With patch being optional.
And `sitl_binary` being of type `SITL` appropriate to feed to `Trace.generate()`

**Comment by ChrisTimperley** [comment]
One way to implement this would be to copy the source code for a given scenario to a temporary directory, to optionally apply a given patch to the code in that directory, and to then build from the temporary directory. To avoid accidentally eating up disk, this method should be implemented as a context manager, as shown below.

```
with scenario.build(patch=patch) as sitl:
  ...
```

The temporary directory would then be automatically destroyed when the context is closed.

**Comment by ChrisTimperley** [comment]
I now have a reasonable version of this implemented. The interface is as follows:
```
with scenario.build(dir_ardupilot, filename_patch=patch) as sitl:
  pass
```
where `dir_ardupilot` specifies the location of a directory containing a clean copy of the ArduPilot git repo (with its submodules updated and initialised).
